services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: thinklm-qdrant
    restart: unless-stopped
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - studybuddylm-net

  backend:
    build: ./server
    container_name: thinklm-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    depends_on:
      - qdrant
    ports:
      - "3000:3000"
    networks:
      - studybuddylm-net

  frontend:
    build: ./client
    container_name: thinklm-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - studybuddylm-net

volumes:
  qdrant_storage:

networks:
  studybuddylm-net:
    external: true
